import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import test from "node:test";

const source=fs.readFileSync(new URL("../static/workspace.mjs",import.meta.url),"utf8");
const start=source.indexOf("function folderForId"),end=source.indexOf("const uiIcons",start);
assert.ok(start>=0&&end>start);
function node(){const names=new Set();return {textContent:"",disabled:false,value:"",dataset:{},classList:{add:x=>names.add(x),remove:x=>names.delete(x),contains:x=>names.has(x)},focus(){},contains(){return false;}};}
function harness(reject=false,deferred=false){
  const nodes=new Map(["folder-delete-modal","folder-delete-name","folder-delete-msg","submit-folder-delete"].map(id=>[id,node()]));
  const state={jobs:[{id:"paper-1",filename:"paper.pdf"}],deletedJobIds:new Set(),draggingJob:null,dragMoveInFlight:null,dragRenderPending:false,dropFolderId:undefined,library:{folders:[{id:"f-1",name:"重点",parent_id:null}],documents:{"paper-1":"f-1"}},expanded:new Set(),deletingFolder:null,folderDeleteInFlight:null,folderDeleteRequest:0};
  const calls=[],pending=[];const context={state,$:id=>nodes.get(id),isDeletedJob:id=>state.deletedJobIds.has(String(id)),document:{querySelectorAll:()=>[]},showFileToast:(...x)=>calls.push(["toast",...x]),renderList:()=>calls.push(["renderList"]),msg:(id,text)=>{nodes.get(id).textContent=text;},open:id=>nodes.get(id).classList.add("open"),close:id=>{nodes.get(id).classList.remove("open");if(id==="folder-delete-modal")state.deletingFolder=null;},post:async(...x)=>{calls.push(["post",...x]);if(reject)throw Error("服务器拒绝");if(deferred)return new Promise(resolve=>pending.push(resolve));return {folders:[],documents:{}};}};
  vm.runInNewContext(source.slice(start,end),context);return {state,nodes,calls,pending,resolve:value=>pending.shift()?.(value),...context};
}
function dragData(){return {types:["application/x-paper2zh-job"],setData(){},effectAllowed:"",dropEffect:""};}

test("known document drag moves to folder and redraws only the list",async()=>{const h=harness();h.startDocumentDrag({dataTransfer:dragData(),currentTarget:node()},{id:"paper-1"});await h.moveDocumentByDrag("f-2",node());assert.equal(h.calls[0][0],"post");assert.equal(h.calls[0][1],"/api/library");assert.equal(h.calls[0][2].action,"move_document");assert.equal(h.calls[0][2].job_id,"paper-1");assert.equal(h.calls[0][2].folder_id,"f-2");assert.equal(h.state.expanded.has("f-2"),true);assert.equal(h.calls.some(x=>x[0]==="renderList"),true);assert.equal(h.calls.some(x=>x[0]==="destroy"||x[0]==="select"),false);});
test("same folder and external drops do not request",async()=>{const h=harness();h.startDocumentDrag({dataTransfer:dragData(),currentTarget:node()},{id:"paper-1"});await h.moveDocumentByDrag("f-1",node());assert.equal(h.calls.some(x=>x[0]==="post"),false);const e={dataTransfer:{types:["Files"]},preventDefault(){this.prevented=true;},stopPropagation(){}};h.documentDrop(e,"f-2",node());assert.equal(e.prevented,undefined);});
test("failed drag keeps association and reports error",async()=>{const h=harness(true);h.startDocumentDrag({dataTransfer:dragData(),currentTarget:node()},{id:"paper-1"});await h.moveDocumentByDrag("f-2",node());assert.equal(h.state.library.documents["paper-1"],"f-1");assert.equal(h.calls.some(x=>x[0]==="toast"),true);});
test("dragend during a pending move cannot submit a second move",async()=>{const h=harness(false,true);h.startDocumentDrag({dataTransfer:dragData(),currentTarget:node()},{id:"paper-1"});const first=h.moveDocumentByDrag("f-2",node());h.clearDocumentDrag();h.startDocumentDrag({dataTransfer:dragData(),currentTarget:node()},{id:"paper-1"});assert.equal(h.calls.filter(x=>x[0]==="post").length,1);assert.equal(h.state.draggingJob,null);h.resolve({folders:[],documents:{"paper-1":"f-2"}});await first;assert.equal(h.state.library.documents["paper-1"],"f-2");});
test("folder deletion supports cancel, submit, and error",async()=>{const h=harness();h.deleteFolder({id:"f-1",name:"重点",parent_id:null});assert.equal(h.nodes.get("folder-delete-name").textContent,"重点");h.close("folder-delete-modal");assert.equal(h.state.deletingFolder,null);h.deleteFolder({id:"f-1",name:"重点",parent_id:null});await h.submitFolderDelete();const request=h.calls.find(x=>x[0]==="post");assert.equal(request[1],"/api/library");assert.equal(request[2].action,"delete_folder");assert.equal(request[2].id,"f-1");assert.equal(h.calls.some(x=>x[0]==="renderList"),true);const f=harness(true);f.deleteFolder({id:"f-1",name:"重点",parent_id:null});await f.submitFolderDelete();assert.equal(f.nodes.get("folder-delete-msg").textContent,"服务器拒绝");assert.equal(f.state.library.documents["paper-1"],"f-1");});
